import 'package:steno_game/repository/lesson_repository.dart';
import 'package:steno_game/repository/multiplayer_stroke_repository.dart';
import 'package:steno_game/repository/picture_quiz_repository.dart';
import 'package:steno_game/repository/stroke_repository.dart';
import 'package:steno_game/repository/topic_repository.dart';
import 'package:steno_game/repository/typing_repository.dart';
import 'package:steno_game/repository/user_repository.dart';
import 'package:steno_game/ui/bottom_sheets/notice/notice_sheet.dart';
import 'package:steno_game/ui/dialogs/info_alert/info_alert_dialog.dart';
import 'package:steno_game/ui/views/home/home_view.dart';
import 'package:steno_game/ui/views/startup/startup_view.dart';
import 'package:stacked/stacked_annotations.dart';
import 'package:stacked_services/stacked_services.dart';
import 'package:steno_game/services/authentication_service.dart';
import 'package:steno_game/services/shared_preference_service.dart';
import 'package:steno_game/services/image_service.dart';
import 'package:steno_game/ui/views/login/login_view.dart';
import 'package:steno_game/ui/views/sign_up/sign_up_view.dart';
import 'package:steno_game/ui/views/forgot_password/forgot_password_view.dart';
import 'package:steno_game/ui/views/achievement/achievement_view.dart';
import 'package:steno_game/ui/views/lessons/lessons_view.dart';
import 'package:steno_game/ui/views/people/people_view.dart';
import 'package:steno_game/ui/views/picture_topic/picture_topic_view.dart';
import 'package:steno_game/ui/views/play/play_view.dart';
import 'package:steno_game/ui/views/profile/profile_view.dart';
import 'package:steno_game/ui/views/quiz_game_stroke/quiz_game_stroke_view.dart';
import 'package:steno_game/ui/views/stroke_exercise/stroke_exercise_view.dart';
import 'package:steno_game/ui/views/strokes_multiplayer/strokes_multiplayer_view.dart';
import 'package:steno_game/ui/views/stroke_play/stroke_play_view.dart';
import 'package:steno_game/ui/views/text_quiz/text_quiz_view.dart';
import 'package:steno_game/ui/views/text_exercise/text_exercise_view.dart';
import 'package:steno_game/ui/views/typing_exercise/typing_exercise_view.dart';
import 'package:steno_game/ui/views/typing_play/typing_play_view.dart';
import 'package:steno_game/ui/views/speed_typing/speed_typing_view.dart';
import 'package:steno_game/ui/bottom_sheets/input_validation/input_validation_sheet.dart';
import 'package:steno_game/ui/views/person/person_view.dart';
import 'package:steno_game/ui/dialogs/update_profile_image/update_profile_image_dialog.dart';
import 'package:steno_game/ui/dialogs/update_name/update_name_dialog.dart';
import 'package:steno_game/ui/dialogs/update_email/update_email_dialog.dart';
import 'package:steno_game/ui/dialogs/update_password/update_password_dialog.dart';
import 'package:steno_game/ui/views/topic/topic_view.dart';
import 'package:steno_game/ui/views/menu/menu_view.dart';
import 'package:steno_game/ui/views/search_steno/search_steno_view.dart';
import 'package:steno_game/ui/views/host_stroke/host_stroke_view.dart';
import 'package:steno_game/ui/views/join_multiplayer_stroke/join_multiplayer_stroke_view.dart';
import 'package:steno_game/ui/views/multiplayer_stroke_waiting_room/multiplayer_stroke_waiting_room_view.dart';
import 'package:steno_game/ui/views/multiplayer_stroke_host/multiplayer_stroke_host_view.dart';
import 'package:steno_game/ui/dialogs/edit_stroke/edit_stroke_dialog.dart';
// @stacked-import

@StackedApp(
  routes: [
    MaterialRoute(page: HomeView),
    MaterialRoute(page: StartupView),
    MaterialRoute(page: LoginView),
    MaterialRoute(page: SignUpView),
    MaterialRoute(page: ForgotPasswordView),
    MaterialRoute(page: AchievementView),
    MaterialRoute(page: LessonsView),
    MaterialRoute(page: PeopleView),
    MaterialRoute(page: PictureTopicView),
    MaterialRoute(page: PlayView),
    MaterialRoute(page: ProfileView),
    MaterialRoute(page: QuizGameStrokeView),
    MaterialRoute(page: StrokeExerciseView),
    MaterialRoute(page: StrokesMultiplayerView),
    MaterialRoute(page: StrokePlayView),
    MaterialRoute(page: TextQuizView),
    MaterialRoute(page: TextExerciseView),
    MaterialRoute(page: TypingExerciseView),
    MaterialRoute(page: TypingPlayView),
    MaterialRoute(page: SpeedTypingView),
    MaterialRoute(page: PersonView),
    MaterialRoute(page: TopicView),
    MaterialRoute(page: MenuView),
    MaterialRoute(page: SearchStenoView),
    MaterialRoute(page: HostStrokeView),
    MaterialRoute(page: JoinMultiplayerStrokeView),
    MaterialRoute(page: MultiplayerStrokeWaitingRoomView),
    MaterialRoute(page: MultiplayerStrokeHostView),
// @stacked-route
  ],
  dependencies: [
    LazySingleton(classType: BottomSheetService),
    LazySingleton(classType: DialogService),
    LazySingleton(classType: NavigationService),
    LazySingleton(classType: AuthenticationService),
    LazySingleton(classType: SharedPreferenceService),
    LazySingleton(classType: ImageService),
    LazySingleton(classType: UserRepository),
    LazySingleton(classType: LessonRepository),
    LazySingleton(classType: TopicRepository),
    LazySingleton(classType: StrokeRepository),
    LazySingleton(classType: PictureQuizRepository),
    LazySingleton(classType: MultiplayerStrokeRepository),
    LazySingleton(classType: TypingRepository),
// @stacked-service
  ],
  bottomsheets: [
    StackedBottomsheet(classType: NoticeSheet),
    StackedBottomsheet(classType: InputValidationSheet),
// @stacked-bottom-sheet
  ],
  dialogs: [
    StackedDialog(classType: InfoAlertDialog),
    StackedDialog(classType: UpdateProfileImageDialog),
    StackedDialog(classType: UpdateNameDialog),
    StackedDialog(classType: UpdateEmailDialog),
    StackedDialog(classType: UpdatePasswordDialog),
    StackedDialog(classType: EditStrokeDialog),
// @stacked-dialog
  ],
)
class App {}
