name: steno_game
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  cloud_firestore: ^4.15.5
  firebase_auth: ^4.17.5
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  google_fonts: ^6.1.0
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  shared_preferences: ^2.2.2
  dartz: ^0.10.1
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7
  firebase_storage: ^11.6.6
  connectivity_plus: ^6.0.1

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.4.5
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/png/ui/
    - assets/png/strokes/

